# Generated by Django 6.0 on 2026-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_remove_topico_citacao_citacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
