# Generated by Django 6.0 on 2026-01-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colinha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colinha',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='colinha',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='colinha',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='colinha',
            old_name='title',
            new_name='titulo',
        ),
    ]
